version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - '80:80'
      - '443:443'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - ./conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
      
  wpcli:
    container_name: wpcli
    image: wordpress:cli-php7.4
    working_dir: /var/www/html
    depends_on:
      - wordpress
      - db
    volumes:
      - wordpress:/var/www/html
      - ./conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    command: "--info"
    user: xfs

volumes:
  wordpress:
  db:
  https-portal-data:
