version: '3.1'

services:

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - wordpress
    environment:
      DOMAINS: >-
        54.199.242.80 -> http://54.199.242.80
      #STAGE: 'staging'  
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/docker-compose.d/certs:/etc/nginx/certs
      - ./server.conf:/etc/nginx/conf.d/server.conf

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
      
volumes:
  wordpress:
  db:
