version: '3.1'

services:

  https-portal:
    image: steveltn/https-portal:1.19.0
    restart: always
    ports:
      - '80:80'
      - '443:443'
    links:
      - wordpress
    environment:
      DOMAINS: 'ufq9r43-3409fjd7.tk -> http://wordpress'
      STAGE: 'production'
    volumes:
      - https-portal-data:/var/lib/https-portal

  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
  https-portal-data:
