version: '3.1'

services:

  https-portal:
    image: steveltn/https-portal:1.19.0
    restart: always
    ports:
      - '80:80'
      - '443:443'
    links:
      - wordpress
    environment:
      DOMAINS: 'ufq9r43-3409fjd5.tk -> http://wordpress, ufq9r43-3409fjd5.tk -> http://nginx'
    volumes:
      - https-portal-data:/var/lib/https-portal

  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      
  nginx:
    image: nginx:1.15-alpine
    restart: always
    volumes:
      - ./goaccess/html:/usr/share/nginx/html
    ports:
      - 7891:80
      
  goaccess:
    image: allinurl/goaccess
    ports:
      - 7890:7890
    restart: always
    volumes:
      - ./goaccess/config:/srv/config
      - ./goaccess/html:/srv/report
      - ./goaccess/logs:/srv/logs
    command: ["--no-global-config", "--config-file=/srv/config/goaccess.conf", "--log-file=/srv/logs/access.log", -e TZ="Asia/Tokyo", -e "LANG=ja_JP.utf8"]

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
  https-portal-data:
  
